### PR TITLE
Supress PID of background task call in README example

### LINKED ISSUE #8: Hide console output on launch
When launching as per the README every first time starting up the WSL machine the following is displayed:
```
[2] 39
[2]  + 39 done       setsid nohup socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork  > /dev/null 2>&1
[2] 44
[2]  + 44 done       setsid nohup socat UNIX-LISTEN:$GPG_AGENT_SOCK,fork  > /dev/null 2>&1
```

Would it be possible to supress this output, I have tried with no luck.

### PR DESCRIPTION
**Pull request by craftbyte**
Closes #8

---
This change is [Reviewable](https://reviewable.io/reviews/blackreloaded/wsl2-ssh-pageant/9)

### CODE REVIEW

**Comment by tobiaskohlbau** [comment]
The braces are not needed on bash. I would advise against putting them in. The lines are confusing enough with all of there flags and parameters.

**Comment by craftbyte** [comment]
Maybe we can add an explanation of that the script does below it?

**Comment by BlackReloaded** [comment]
> Maybe we can add an explanation of that the script does below it?

This is a good idea but i think for a new PR.

@craftbyte can you make that?

**Comment by tobiaskohlbau** [comment]
@craftbyte my mistake, I thought there where different examples for bash and zsh.

**Pull request merged**
